### ISSUE TITLE
Without mut?

### ISSUE THREAD

**Issue by moonglum** [badboy/hack-and-learn-testing#4]
Hello :smile: I'm working a little on the hangman exercise. I wrote the following code:

``` rust
let mut guesses = game.guesses; // game.guesses is a Vec<char>
guesses.push(guess); // guess is a char
```

I wanted to ask if it is possible to write this without the `mut`: Is there a way to create a new Vec from a Vec and another Vec (or an element that should be in that new Vec)?

/cc @badboy, @mre

**Comment by badboy** [comment]
You could of course clone the old vector, append to it, then make it immutable: http://is.gd/QEoNps
But Rust's stdlib has no real immutable data structures (as for a simple implementation for a Vector this would involve a lot of copying, so better make it explicit by letting the user do it)

My small example could be optimized though by allocating the new vector upfront with length `vec.len() + 1`, then copying over the data.

**Comment by moonglum** [comment]
Thanks, @badboy :smile:
